/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a gpservice_adaptor.h: gpservice.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef GPSERVICE_ADAPTOR_H
#define GPSERVICE_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.yuezk.qt.GPService
 */
class GPServiceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.yuezk.qt.GPService")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.yuezk.qt.GPService\">\n"
"    <signal name=\"connected\"/>\n"
"    <signal name=\"disconnected\"/>\n"
"    <signal name=\"logAvailable\">\n"
"      <arg type=\"s\" name=\"log\"/>\n"
"    </signal>\n"
"    <method name=\"connect\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"server\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"username\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"passwd\"/>\n"
"    </method>\n"
"    <method name=\"disconnect\"/>\n"
"    <method name=\"status\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    GPServiceAdaptor(QObject *parent);
    virtual ~GPServiceAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void connect(const QString &server, const QString &username, const QString &passwd);
    void disconnect();
    int status();
Q_SIGNALS: // SIGNALS
    void connected();
    void disconnected();
    void logAvailable(const QString &log);
};

#endif
