name: globalprotect-openconnect
base: core18
version: 'test'
summary: A GlobalProtect VPN client powered by OpenConnect
description: |
  A GlobalProtect VPN client (GUI) for Linux based on OpenConnect and built with Qt5, supports SAML auth mode.

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

package-repositories:
  - type: apt
    ppa: beineri/opt-qt-5.12.10-bionic

apps:
  gpclient:
    common-id: com.yuezk.qt.gpclient.desktop
    command: desktop-launch gpclient
    desktop: usr/share/applications/com.yuezk.qt.gpclient.desktop
    environment:
      QT_DEBUG_PLUGINS: 1
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - x11
      - network
    # extensions:
    #   - kde-neon

parts:
  application:
    plugin: nil
    source: snap/local/globalprotect-openconnect.tar.gz

    build-packages:
      - g++
      - make
      - qt512base
      - qt512websockets
      - qt512webengine

    stage-packages:
      - qt512base
      - qt512websockets
      - qt512webengine

    # build-packages:
    #   - g++
    #   - make
    #   - qt5-qmake
    #   - qtwebengine5-dev
    #   - libqt5websockets5-dev
    
    # build-snaps:
    #   - kde-frameworks-5-qt-5-14-core18-sdk
    
    # stage-packages:
    #   - libqt5widgets5
    #   - libqt5webengine5
    #   - libqt5webenginewidgets5
    #   - libqt5websockets5

    override-build: |
      QT_BASE_DIR=/opt/qt512

      export QTDIR=$QT_BASE_DIR
      export PATH=$QT_BASE_DIR/bin:$PATH
      export LD_LIBRARY_PATH=$QT_BASE_DIR/lib/x86_64-linux-gnu:$QT_BASE_DIR/lib:$LD_LIBRARY_PATH
      export PKG_CONFIG_PATH=$QT_BASE_DIR/lib/pkgconfig:$PKG_CONFIG_PATH

      qmake CONFIG+=release
      make
      make install INSTALL_ROOT="${SNAPCRAFT_PART_INSTALL}"

