name: globalprotect-openconnect
base: core18
version: 'test'
summary: A GlobalProtect VPN client powered by OpenConnect
description: |
  A GlobalProtect VPN client (GUI) for Linux based on OpenConnect and built with Qt5, supports SAML auth mode.

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

package-repositories:
  - type: apt
    ppa: beineri/opt-qt-5.12.9-bionic

parts:
  application:
    plugin: qmake
    source: snap/local/globalprotect-openconnect.tar.gz
    build-packages:
      - qtbase5-dev
      - qttools5-dev
      - libqt5websockets5-dev
      - qtwebengine5-dev

