[package]
name = "gphip"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gpapi = { path = "../gpapi" }
anyhow.workspace = true
askama.workspace = true
chrono.workspace = true
netdev.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
uuid = { workspace = true, features = ["v5"] }
uzers.workspace = true
xmltree.workspace = true
