name: globalprotect-openconnect
base: core18
confinement: strict
compression: lzo

license: GPL-3.0

adopt-info: application

package-repositories:
  - type: apt
    ppa: dwmw2/openconnect

layout:
  /usr/local/sbin:
    bind: $SNAP/usr/sbin
  /usr/share/vpnc-scripts:
    bind: $SNAP/usr/share/vpnc-scripts
  /usr/share/locale:
    bind: $SNAP/usr/share/locale

slots:
  gpservice-slot:
    interface: dbus
    bus: system
    name: com.yuezk.qt.GPService

plugs:
  gpservice-plug:
    interface: dbus
    bus: system
    name: com.yuezk.qt.GPService

apps:
  gpservice:
    common-id: com.yuezk.qt.gpservice
    daemon: simple
    command: usr/bin/gpservice
    command-chain:
      - snap/command-chain/desktop-launch
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    plugs:
      - network
    slots: 
      - gpservice-slot

  gpclient:
    common-id: com.yuezk.qt.gpclient
    command: usr/bin/gpclient
    desktop: usr/share/applications/com.yuezk.qt.gpclient.desktop
    extensions:
      - kde-neon
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - network
      - gpservice-plug

parts:
  application:
    override-pull: |
      snapcraftctl pull

      VERSION=$(cat VERSION)
      GRADE="stable"

      if echo "$VERSION" | grep -q "snapshot"
      then
          GRADE="devel"
      fi

      snapcraftctl set-version "$VERSION"
      snapcraftctl set-grade "$GRADE"
    parse-info:
      - usr/share/metainfo/com.yuezk.qt.gpclient.metainfo.xml
    plugin: cmake
    source: .
    build-packages:
      - libglu1-mesa-dev
    build-snaps:
      - kde-frameworks-5-core18-sdk
    stage-packages:
      - openconnect
      - libatm1
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release