name: globalprotect-openconnect
base: core18
version: 'test'
grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots
compression: lzo

contact: k3vinyue@gmail.com
donation: https://www.buymeacoffee.com/yuezk
issues: https://github.com/yuezk/GlobalProtect-openconnect/issues
source-code: https://github.com/yuezk/GlobalProtect-openconnect
website: https://github.com/yuezk/GlobalProtect-openconnect
license: GPL-3.0

adopt-info: application

package-repositories:
  - type: apt
    ppa: dwmw2/openconnect

layout:
  /usr/local/sbin:
    bind: $SNAP/usr/sbin
  /usr/share/vpnc-scripts:
    bind: $SNAP/usr/share/vpnc-scripts
  /usr/share/locale:
    bind: $SNAP/usr/share/locale

slots:
  gpservice-slot:
    interface: dbus
    bus: system
    name: com.yuezk.qt.GPService

plugs:
  gpservice-plug:
    interface: dbus
    bus: system
    name: com.yuezk.qt.GPService

apps:
  gpservice:
    daemon: simple
    command: usr/bin/gpservice
    command-chain:
      - snap/command-chain/desktop-launch
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    plugs:
      - network
    slots: 
      - gpservice-slot

  gpclient:
    common-id: com.yuezk.qt.gpclient
    command: usr/bin/gpclient
    desktop: usr/share/applications/com.yuezk.qt.gpclient.desktop
    extensions:
      - kde-neon
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - network
      - gpservice-plug

parts:
  application:
    parse-info:
      - usr/share/metainfo/com.yuezk.qt.gpclient.metainfo.xml
    plugin: cmake
    source: .
    build-packages:
      - libglu1-mesa-dev
    build-snaps:
      - kde-frameworks-5-core18-sdk
    stage-packages:
      - openconnect
      - libatm1
    configflags:
      - -DCMAKE_BUILD_TYPE=Release