name: globalprotect-openconnect
base: core18
version: 'test'
summary: A GlobalProtect VPN client powered by OpenConnect
description: |
  A GlobalProtect VPN client (GUI) for Linux based on OpenConnect and built with Qt5, supports SAML auth mode.

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

package-repositories:
  - type: apt
    ppa: beineri/opt-qt-5.12.10-bionic
  - type: apt
    ppa: dominik-stadler/dsta-bionic-ppa

slots:
  gpservice-slot:
    interface: dbus
    bus: system
    name: com.yuezk.qt.GPService

plugs:
  gpservice-plug:
    interface: dbus
    bus: system
    name: com.yuezk.qt.GPService

apps:
  gpservice:
    daemon: simple
    command: usr/bin/gpservice
    environment:
      LANG: en_US.utf8
    plugs:
      - network
    # slots: 
    #   - gpservice-slot

  gpclient:
    common-id: com.yuezk.qt.gpclient.desktop
    command: usr/bin/gpclient
    desktop: usr/share/applications/com.yuezk.qt.gpclient.desktop
    environment:
      QT_PLUGIN_PATH: $SNAP/opt/qt512/plugins
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - network
      - gpservice-plug

parts:
  application:
    plugin: nil
    source: .

    build-packages:
      - g++
      - make
      - libgl1-mesa-dev
      - qt512base
      - qt512websockets
      - qt512webengine

    stage-packages:
      - qt512base
      - qt512websockets
      - qt512webengine

    override-build: |
      QT_BASE_DIR=/opt/qt512

      export QTDIR=$QT_BASE_DIR
      export PATH=$QT_BASE_DIR/bin:$PATH
      export LD_LIBRARY_PATH=$QT_BASE_DIR/lib/x86_64-linux-gnu:$QT_BASE_DIR/lib:$LD_LIBRARY_PATH
      export PKG_CONFIG_PATH=$QT_BASE_DIR/lib/pkgconfig:$PKG_CONFIG_PATH

      qmake CONFIG+=release
      make
      make install INSTALL_ROOT="${SNAPCRAFT_PART_INSTALL}"

