name: Build

on:
  push:
    branches:
      - develop
    tags:
      - "v*.*.*"
    paths-ignore:
      - LICENSE
      - "*.md"
      - .vscode
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    
    runs-on: ${{ matrix.os }}

    steps:
      # Checkout repository and submodules
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build
        run: |
          ./scripts/install-ubuntu.sh

  snapshot-archive-all:
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git-archive-all
      
      - name: Archive all
        run: |
          ./scripts/snapshot-archive-all.sh

      - uses: actions/upload-artifact@v2
        with:
          name: snapshot-source-code
          path: ./artifacts/*

  snapshot-ppa:
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    needs: snapshot-archive-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: snapshot-source-code
          path: artifacts
      
      - name: Extract source code
        run: |
          cd $GITHUB_WORKSPACE/artifacts
          mkdir deb-build && cp *.tar.gz deb-build && cd deb-build
          tar xf *.tar.gz

      - name: Publish PPA
        uses: yuezk/publish-ppa-package@develop
        with:
          repository: 'ppa:yuezk/globalprotect-openconnect-snapshot'
          gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
          pkgdir: '${{ github.workspace }}/artifacts/deb-build/globalprotect-openconnect*/'
      
  snapshot-aur:
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    needs: snapshot-archive-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: snapshot-source-code
          path: artifacts

      - name: Publish AUR package
        env:
          VERSION: $(cat ./artifacts/VERSION)
        uses: yuezk/github-actions-deploy-aur@update-pkgver
        with:
          pkgname: globalprotect-openconnect-git
          pkgbuild: ./artifacts/aur/PKGBUILD
          assets: ./artifacts/aur/*.tar.gz
          update_pkgver: true
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: 'Snapshot release: git#${{ github.sha }}'

  snapshot-obs:
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    needs: snapshot-archive-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: snapshot-source-code
          path: artifacts

      - uses: yuezk/publish-obs-package@main
        with:
          project: home:yuezk
          package: globalprotect-openconnect-snapshot
          username: yuezk
          password: ${{ secrets.OBS_PASSWORD }}
          files: ./artifacts/obs/*

  snapshot-snap:
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    needs: snapshot-archive-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: snapshot-source-code
          path: artifacts
      
      - name: Extract source code
        run: |
          mkdir snap-source
          tar xvf ./artifacts/globalprotect-openconnect-*tar.gz \
            --directory snap-source \
            --strip 1
          
      - uses: snapcore/action-build@v1
        id: build
        with:
          path: ./snap-source

      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.SNAPSTORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge

  release-archive-all:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git-archive-all
      
      - name: Archive all
        run: |
          ./scripts/release-archive-all.sh

      - uses: actions/upload-artifact@v2
        with:
          name: release-source-code
          path: ./artifacts/*

  release-ppa:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: release-archive-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-source-code
          path: artifacts

      - name: Extract source code
        run: |
          cd $GITHUB_WORKSPACE/artifacts
          mkdir deb-build && cp *.tar.gz deb-build && cd deb-build
          tar xf *.tar.gz

      - name: Publish PPA
        uses: yuezk/publish-ppa-package@develop
        with:
          repository: 'ppa:yuezk/globalprotect-openconnect'
          gpg_private_key: ${{ secrets.PPA_GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.PPA_GPG_PASSPHRASE }}
          pkgdir: '${{ github.workspace }}/artifacts/deb-build/globalprotect-openconnect*/'
  
  release-aur:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: release-archive-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-source-code
          path: artifacts

      - name: Publish AUR package
        env:
          VERSION: $(cat ./artifacts/VERSION)
        uses: yuezk/github-actions-deploy-aur@update-pkgver
        with:
          pkgname: globalprotect-openconnect
          pkgbuild: ./artifacts/aur/PKGBUILD
          assets: ./artifacts/aur/*.tar.gz
          update_pkgver: true
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: 'Release ${{ github.ref }}'
  
  release-obs:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: release-archive-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-source-code
          path: artifacts

      - uses: yuezk/publish-obs-package@main
        with:
          project: home:yuezk
          package: globalprotect-openconnect
          username: yuezk
          password: ${{ secrets.OBS_PASSWORD }}
          files: ./artifacts/obs/*
  
  release-github:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - release-ppa
      - release-aur
      - release-obs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: release-source-code
          path: artifacts
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ./artifacts/*.tar.gz
