name: Build

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - LICENSE
      - "*.md"
      - .vscode
  pull_request:
    branches:
      - master
      - dev
    paths-ignore:
      - LICENSE
      - "*.md"
      - .vscode
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      # Checkout repository and submodules
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build & Install
        run: |
          ./scripts/install-ubuntu.sh